#!/bin/bash

# Retrieve the Public IP address
public_ip_address=$(curl -s https://api.ipify.org)

# Retrieve the Local IP address
local_ip_address=$(hostname -I | awk '{print $1}')

echo " "
# Print the Public IP address
echo "Public IP address: $public_ip_address"

echo " "
# Print the Local IP address
echo "Local IP address: $local_ip_address"

# Email configuration
recipient="<momen.amin@hotmail.com>"

echo " "
# Send email with IP address
echo "Public IP address: $public_ip_address" | mail -s "Public IP Address" "${recipient}"
echo " "
