#!/bin/bash

# Retrieve the Public IP address
public_ip_address=$(curl -s https://api.ipify.org)

# Retrieve the Local IP address
local_ip_address=$(hostname -I | awk '{print $1}')

echo " "
# Print the Public IP address
echo "Public IP address: $public_ip_address"

echo " "
# Print the Local IP address
echo "Local IP address: $local_ip_address"

# Email configuration
recipient="<momen.amin@hotmail.com>"

TO="momen.amin@hotmail.com"
SUBJECT="The Public SSH Key has been added to a Server!"
BODY1=Public IP address: "$public_ip_address"
BODY2=Local IP address: "$local_ip_address"

echo " "
# Send email with IP address
echo "Public IP address: $public_ip_address" | mail -s "Public IP Address" "${recipient}"
echo " "
echo "$SUBJECT: $public_ip_address"\n"$local_ip_address" | mail -s "Public IP Address" "${recipient}"
echo " "
echo "${BODY1}"\n"${BODY2}" | mail -s "${SUBJECT}" "${TO}"
echo " "
