#!/bin/bash

# Retrieve the Public IP address
public_ip_address=$(curl -s https://api.ipify.org)

# Retrieve the Local IP address
local_ip_address=$(hostname -I | awk '{print $1}')

echo " "
# Print the Public IP address
echo "Public IP address: $public_ip_address"

echo " "
# Print the Local IP address
echo "Local IP address: $local_ip_address"

# Email configuration
recipient="<momen.amin@hotmail.com>"

TO="momen.amin@hotmail.com"
SUBJECT="Public & Local IP addresses"
BODY1="$public_ip_address"
BODY2="$local_ip_address"

echo " "
# Send email with IP address
echo "Public IP address: $public_ip_address" | mail -s "Public IP Address" "${recipient}"
echo " "
echo "Subject:\n${BODY1}" "${BODY2}" | mail -s "${SUBJECT}" "${TO}"
echo " "
